id: 255c5a29016943d48bd570327ee8736b
initial_creation_type: ocr
source_metadata:
  volumes:
    d884e5d369314df9bcf3599f4224d7b6:
      base_file: v022.txt
      image_group_id: I1PD95867
      title: ''
      total_pages: 1409
      volume_number: 22
